services:
  db:
    image: mysql:8.0
    container_name: sistemamype_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sistemamype
      MYSQL_USER: inventario
      MYSQL_PASSWORD: inventario123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/02_seed_base.sql:/docker-entrypoint-initdb.d/02_seed_base.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistemamype_backend
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

    # 👇 ESTA ES LA PARTE IMPORTANTE
    command: >
      sh -c "python -m app.db.init_db &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data: